version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.7
    commands:
      - env | grep "CODEBUILD"
      - env | grep "JUNPU"
      - python3 -m pip install pip==20.2.4
      - python3 -m pip install --use-feature=2020-resolver black==20.8b1 flake8=3.8.4
      - python3 -m pip list
      - python3 -m site
      - eval "${JUNPU_INSTALL_COMMANDS}"
    finally:
      - eval "${JUNPU_INSTALL_FINALLY}"

  pre_build:
    commands:
      - eval "${JUNPU_PRE_BUILD_COMMANDS}"
    finally:
      - eval "${JUNPU_PRE_BUILD_FINALLY}"

  build:
    commands:
      - eval "${JUNPU_BUILD_COMMANDS}"
    finally:
      - eval "${JUNPU_BUILD_FINALLY}"

  post_build:
    commands:
      - eval "${JUNPU_POST_BUILD_COMMANDS}"
    finally:
      - eval "${JUNPU_POST_BUILD_FINALLY}"
