version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.7
    commands:
      - env | grep "CODEBUILD"
      - env | grep "JUNPU"
      - python3 -m venv env
      - source ./env/bin/activate
      - which python3
      - python3 -m pip install --upgrade pip
      - python3 -m pip install --use-feature=2020-resolver --requirement requirements.txt
      - python3 -m pip list
      - python3 -m site
      - eval "${JUNPU_INSTALL_COMMANDS}"
    finally:
      - eval "${JUNPU_INSTALL_FINALLY}"

  pre_build:
    commands:
      - eval "${JUNPU_PRE_BUILD_COMMANDS}"
      - python3 run.py --log-filepath "${CODEBUILD_SRC_DIR}/.tmp/${CODEBUILD_LOG_PATH}.log"
    finally:
      - eval "${JUNPU_PRE_BUILD_FINALLY}"

  build:
    commands:
      - eval "${JUNPU_BUILD_COMMANDS}"
    finally:
      - eval "${JUNPU_BUILD_FINALLY}"

  post_build:
    commands:
      - eval "${JUNPU_POST_BUILD_COMMANDS}"
    finally:
      - eval "${JUNPU_POST_BUILD_FINALLY}"

artifacts:
  files:
    - "${CODEBUILD_SRC_DIR}/.tmp/${CODEBUILD_LOG_PATH}.log"