version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.7
    commands:
      - eval "${JUNPU_INSTALL_COMMANDS}"
    finally:
      - eval "${JUNPU_INSTALL_FINALLY}"
      - env | grep "(CODEBUILD|JUNPU)"

  pre_build:
    commands:
      - eval "${JUNPU_PRE_BUILD_COMMANDS}"
    finally:
      - eval "${JUNPU_PRE_BUILD_FINALLY}"

  build:
    commands:

      - eval "${JUNPU_BUILD_COMMANDS}"
    finally:
      - eval "${JUNPU_BUILD_FINALLY}"

  post_build:
    commands:
      - eval "${JUNPU_POST_BUILD_COMMANDS}"
    finally:
      - eval "${JUNPU_POST_BUILD_FINALLY}"
