version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.7

  pre_build:
    commands:
      - env | grep "CODEBUILD"
      - eval "${PRE_BUILD_COMMAND}"

  build:
    commands:
      - eval "${BUILD_COMMAND}"

  post_build:
    commands:
      - eval "${POST_BUILD_COMMAND}"
